---
- name: Restart PBS Service
  ansible.builtin.service:
    name: proxmox-backup
    state: restarted

- name: Restart PBS Proxy
  ansible.builtin.service:
    name: proxmox-backup-proxy
    state: restarted
